class Localization {

  static String currentLocal = 'ru';

  static Map<String, Map<String, String>> _words = {
    'ru': {
      'Profile' : 'Профиль',
      'Restaurants': 'Заведения',
      'Orders': 'Заказы',
      'Order' : 'Заказ',
      'Order details' : 'Детали заказа',
      'the order will be ready in': 'заказ будет готов через',
      'Address': 'Адрес',
      'When' : 'Когда',
      'My order': 'Мой заказ',
      'Total price': 'Итого',
      'In process' : 'В процессе',
      'Ready': 'Готов',
      'Not payed': 'Не оплачен',
      'No orders': 'Нет заказов',
      'Ordered at': 'Сделан',
      'RUB' : 'р',
      'd': 'д',
      'h': 'ч',
      'min': 'мин',
      'Open now' : 'Открыто',
      'Closed now': 'Закрыто',
      'Far away': 'Далеко',
      'Open till' : 'Открыто до',
      'Menu': 'Меню',
      'items': 'блюд',
      'BUY' : 'КУПИТЬ',
      'kcal': 'ккал',
      'ADD TO CART': 'В КОРЗИНУ',
      'PROCESS ORDER': 'ОПЛАТА',
      'Cart': 'Корзина',
      'DATE': 'ДАТА',
      'TIME': 'ВРЕМЯ',
      'PAY': 'ОПЛАТИТЬ',
      'FINISH ORDER': 'ЗАКОНЧИТЬ ЗАКАЗ',
      'Show more': 'Информация',
      'Week': 'Неделя',
      'Month': 'Месяц',
      'Total': 'Всего',
      'History': 'История',
      'Logout': 'Выход',
      'Finished': 'Успешно',
      'Remove': 'Удалить',
      'Do you want to remove item from your cart?': 'Вы хотите удалить заказ из корзины?',
      'YES': 'ДА',
      'NO': 'НЕТ',
      'Email': 'Почта',
      'Not a valid email': 'Неверная почта',
      'Password': 'Пароль',
      'Password too short': 'Пароль слишком короткий',
      'LOG IN': 'ВОЙТИ',
      'FORGOT PASSWORD': 'ЗАБЫЛ ПАРОЛЬ',
      'added to your cart': 'добавлен в корзину',
      'Wrong item': 'Ошибка',
      'Cannot add item from another restaurant. Please, finish your current order': 'Невозможно добавить в корзину. Пожалуйста, завершите текущий заказ',
      'OK': 'ОК',
      'Order history': 'История заказов',
      'No date or time': 'Когда?',
      'Please, select date and time': 'Пожалуйста, укажите дату и время',
      'Wrong time': 'Неверное время',
      'Please, select time in range': 'Пожалуйста, выберете время в отрезке',
      'Error': 'Ошибка',
      'Please, try again later': 'Пожалуйста, попробуйте позже',
      'Success': 'Успех',
      'Your order was created': 'Ваш заказ был создан',
      'No date': 'Дата не указана',
      'Please, select the date': 'Пожалуйста, выберите дату',
      'Statistics': 'Статистика',
      'Visited places': 'Мест посещено',
      'Items ordered': 'Блюд заказано',
      'Money spent': 'Денег потрачено',
      'Money saved': 'Денег сэкономлено',
      'First name': 'Имя',
      'Last name': 'Фамилия',
      'Enter your first name': 'Введите ваше имя',
      'Enter your last name': 'Введите вашу фамилию',
      'Phone': 'Телефон',
      'Enter valid phone': 'Введите валидный номер',
      'SIGN UP': 'РЕГИСТРАЦИЯ',
      'Please, add some items to your cart': 'Пожалуйста, добавьте блюда в корзину',
      'Empty cart': 'Пустая корзина',
      'Wrong email or password': 'Неверная почта или пароль',
      'Unauthorized': 'Не авторизован',
      'Email already taken': 'Почта уже занята',
      'Not registered': 'Ошибка',
      'Variants': 'Варианты',
      'WITH ME': 'С СОБОЙ',
      'ON PLACE': 'НА МЕСТЕ',
      'People count': 'Количесто человек',
      'Map': 'Карта'
    }
  };

  static String word(String word){
    return _words[currentLocal][word];
  }
}